branches:
  only:
    - master
    - develop
    - setup_travis


matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8

before_install:
  - git submodule update --init --remote --merge --recursive
  - git clone -b master https://$GITHUB_USER:$GITHUB_PWD@github.com/IBM-Swift/BluePic-Testing-Credentials.git
  - cd BluePic-Server
  - cd Package-Builder
  - git checkout testing_repo
  - cd ..
   
script:
  - ./Package-Builder/build-package.sh $TRAVIS_BRANCH $TRAVIS_BUILD_DIR/BluePic-Server ..BluePic-Testing-Credentials BluePic $TRAVIS_BUILD_DIR
  - cd ../BluePic-iOS
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild -workspace BluePic.xcworkspace/ -scheme BluePic -sdk iphonesimulator10.0 ONLY_ACTIVE_ARCH=NO; fi