branches:
  only:
    - master
    - develop
    - setup_travis


matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8
      #podfile: BluePic-iOS/Podfile
      #xcode_project: BluePic-iOS/BluePic.xcodeproj
      #xcode_scheme: BluePic

before_install:
  - git submodule update --init --remote --merge --recursive
  - git clone -b master https://$GITHUB_USER:$GITHUB_PWD@github.com/IBM-Swift/BluePic-Testing-Credentials.git
  - cp -RP $TRAVIS_BUILD_DIR/BluePic-Testing-Credentials/development/* $TRAVIS_BUILD_DIR
  - cd BluePic-Server
  - cd Package-Builder
  - git checkout sample
  - cd ..
 
script:
  - ./Package-Builder/build-package.sh $TRAVIS_BRANCH $TRAVIS_BUILD_DIR/BluePic-Server BluePic-Testing-Credentials