language: objective-c

branches:
  only:
    - master
    - develop
    - add-travis

podfile: BluePic-iOS/Podfile
xcode_project: BluePic-iOS/BluePic.xcodeproj
xcode_scheme: BluePic

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8

before_install:
  - git submodule update --init --remote --merge --recursive

script:
  - cd BluePic-Server; ./Package-Builder/build-package.sh $TRAVIS_BRANCH $TRAVIS_BUILD_DIR/BluePic-Server
 