language: objective-c

branches:
  only:
    - master
    - develop
    - add-travis

podfile: BluePic-iOS/Podfile

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8

before_install:
  - git submodule update --init --remote --merge --recursive

  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update   ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install curl openssl; fi

  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://swift.org/builds/swift-3.0-release/ubuntu1404/swift-3.0-RELEASE/swift-3.0-RELEASE-ubuntu14.04.tar.gz    ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar xzvf swift-3.0-RELEASE-ubuntu14.04.tar.gz    ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$PWD/swift-3.0-RELEASE-ubuntu14.04/usr/bin:$PATH    ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install clang-3.8 ; fi
  # - cd BluePic-Server

script:
  - cd BluePic-Server; ./Package-Builder/build-package.sh $TRAVIS_BRANCH $TRAVIS_BUILD_DIR/BluePic-Server
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd ../BluePic-iOS; xcodebuild clean build test -project BluePic.xcodeproj -scheme BluePic; fi
 