branches:
  only:
    - master
    - develop
    - setup_travis


matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8

before_install:
  - git submodule update --init --remote --merge --recursive
  - git clone -b master https://$GITHUB_USER:$GITHUB_PWD@github.com/IBM-Swift/BluePic-Testing-Credentials.git
  - cp -rP BluePic-Testing-Credentials/BluePic/* .
  - cd BluePic-Server
   
script:
  - ./Package-Builder/build-package.sh $TRAVIS_BRANCH $TRAVIS_BUILD_DIR/BluePic-Server BluePic-Testing-Credentials
  - cd ../BluePic-iOS
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild -project BluePic.xcodeproj/ -target BluePic -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO; fi